language: java
jdk:
  - openjdk7
  - oraclejdk7
script: "./travis.sh"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d50931f8bba3694960c2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
