---
baseurl: "http://go-ide.com/"
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
languageCode: "en-us"
title: "IntelliJ Go"
theme: "blackburn"
paginate: 10
canonifyurls: true
indexes:
  categories: "categories"
  tag: "tags"
  topic: "topics"

params: 
  brand: "IntelliJ Go"
  subtitle: "Golang plugin for IntelliJ-based IDEs"
  highlightjs: "androidstudio"
  dateFormat: "02 Jan 2006, 15:04"
  
menu:
  main:
      - name: "Home"
        pre: "<i class='fa fa-home' style='width: 1em;'></i>"
        weight: 0
        identifier: "home"
        url: "/"
      - name: "Releases"
        pre: "<i class='fa' style='width: 1em;'></i>"
        weight: 1
        identifier: "releases"
        url: "/topics/releases"
      - name: "Alpha"
        pre: "<i class='fa' style='width: 1em;'></i>"
        weight: 2
        identifier: "alpha"
        url: "/topics/alpha"

social:
 github: "go-lang-plugin-org/go-lang-idea-plugin"